SELECT 
    CASE 
        WHEN TIMESTAMPDIFF(YEAR, BIRTHDATE, CURDATE()) < 18 THEN 'Under 18'
        WHEN TIMESTAMPDIFF(YEAR, BIRTHDATE, CURDATE()) BETWEEN 18 AND 35 THEN '18-35'
        WHEN TIMESTAMPDIFF(YEAR, BIRTHDATE, CURDATE()) BETWEEN 36 AND 55 THEN '36-55'
        WHEN TIMESTAMPDIFF(YEAR, BIRTHDATE, CURDATE()) BETWEEN 56 AND 75 THEN '56-75'
        ELSE '75+'
    END AS age_group,
    COUNT(*) AS patient_count
FROM patients
GROUP BY age_group
ORDER BY age_group;

SELECT GENDER, COUNT(*) AS patient_count
FROM patients
GROUP BY GENDER;